name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Third
      id: third
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Third
        setup-command: pip install nbformat
        command: python ./run_test.py
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        THIRD_RESULTS: "${{steps.third.outputs.result}}"
      with:
        runners: third